### Index
GET http://localhost:5000/

### Create User
POST http://localhost:5000/register
Content-Type: application/json

{
    "name": "Edward",
    "email": "edward@pasenidis.com",
    "password": "testpass"
}

### Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "edward@pasenidis.com",
    "password": "testpass"
}

### Current User
GET  http://localhost:5000/currentUser
Content-Type: application/json
Authorization: Bearer <TOKEN>
